apiVersion: batch/v1
kind: Job
metadata:
  name: hello-job
spec:
  selector: {}
  template:
    metadata:
      name: hello-world-job
    spec:
      containers:
        - name: hello-world-job
          image: quay.io/practicalopenshift/hello-world
      restartPolicy: OnFailure