apiVersion: batch/v1
kind: Job
metadata:
  name: hello-job
spec:
  template:
    spec:
      containers:
      - name: process
        image: busybox
        command: ["sh", "-c", "echo Starting job... && sleep 5 && echo Job complete."]
      restartPolicy: Never