apiVersion: v1
kind: Pod
metadata:
  name: hello-world-pod-2
  labels:
    app: hello-world-pod-2
spec:
  containers:
  - env:
    - name: MESSAGE
      value: Hi! I'm an environment variable in pod 2
    image: quay.io/practicalopenshift/hello-world
    imagePullPolicy: Always
    name: hello-world-override
    resources:
      requests:
        cpu: "250m" # Requests 250 millicores of CPU
        memory: "128Mi" # Requests 128 MiB of memory
      limits:
        cpu: "500m" # Limits to 500 millicores of CPU
        memory: "256Mi" # Limits to 256 MiB of memory
